package ZWayJNIWrapper;

import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public final class ZWay {
    public final static int deviceAdded = 0x01;
    public final static int deviceRemoved = 0x02;
    public final static int instanceAdded = 0x04;
    public final static int instanceRemoved = 0x08;
    public final static int commandAdded = 0x10;
    public final static int commandRemoved = 0x20;
    private final long jzway;

    public Controller controller;
    public Map<Integer, Device> devices;

    static {
        System.loadLibrary("jzway");
    }

    public ZWay(String name, String port, int speed, String config_folder, String translations_folder, String zddx_folder, long ternminator_callback) throws Exception {
        jzway = jni_zwayInit(name, port, speed, config_folder, translations_folder, zddx_folder, ternminator_callback);

        controller = new Controller();
        devices = new HashMap<>();
    }

    public void discover() {
        jni_discover(jzway);
    }

    // Controller methods

    public boolean isRunning() { return jni_isRunning(jzway); }

    /* BEGIN AUTOGENERATED CC TEMPLATE
    public Device.Instance.%cc_capitalized_name% %cc_camel_case_name%(Integer deviceId, Integer instanceId) {
        return ((ZWay.Device.Instance.%cc_capitalized_name%) devices.get(deviceId).instances.get(instanceId).commandClassesByName.get("%cc_camel_case_name%"));
    }
    * END AUTOGENERATED CC TEMPLATE */

    public static Type commandClassClassById(Integer id) {
        switch (id) {
            /* BEGIN AUTOGENERATED CC TEMPLATE
            case %cc_id%:
                return ZWay.Device.Instance.%cc_capitalized_name%.class;
            * END AUTOGENERATED CC TEMPLATE */
            default:
                return null;
        }
    }

    public static String commandClassNameById(Integer id) {
        switch (id) {
            /* BEGIN AUTOGENERATED CC TEMPLATE
            case %cc_id%:
                return "%cc_camel_case_name%";
            * END AUTOGENERATED CC TEMPLATE */
            default:
                return null;
        }
    }

    // Callback stub
    
    private void successCallback(Object obj) {
        System.out.println("successCallback");
    }

    private void failureCallback(Object obj) {
        System.out.println("failureCallback");
    }

    private void deviceCallback(int type, int deviceId, int instanceId, int commandClassId) throws Exception {
        if (type == deviceAdded) {
            System.out.println("Device added " + deviceId);
            Device device = new Device(this, deviceId);
            this.devices.put(deviceId, device);
            device.instances.put(0, device.new Instance(this, device, 0));
        } else if (type == deviceRemoved) {
            System.out.println("Device removed " + deviceId);
            devices.remove(deviceId);
        } else if (type == instanceAdded) {
            System.out.println("Instance added " + deviceId + ":" + instanceId);
            Device device = devices.get(deviceId);
            device.instances.put(instanceId, device.new Instance(this, device, instanceId));
        } else if (type == instanceRemoved) {
            System.out.println("Instance removed " + deviceId + ":" + instanceId);
            devices.get(deviceId).instances.remove(instanceId);
        } else if (type == commandAdded) {
            System.out.println("Command Class added " + deviceId + ":" + instanceId + " " + commandClassId);
            Device device = devices.get(deviceId);
            Device.Instance instance = device.instances.get(instanceId);
            switch (commandClassId) {
                /* BEGIN AUTOGENERATED CC TEMPLATE
                case %cc_id%:
                    Device.Instance.%cc_capitalized_name% command%cc_capitalized_name% = instance.new %cc_capitalized_name%(this, instance);
                    instance.commandClasses.put(commandClassId, command%cc_capitalized_name%);
                    instance.commandClassesByName.put("%cc_camel_case_name%", command%cc_capitalized_name%);
                    break;
                 * END AUTOGENERATED CC TEMPLATE */
            }
        } else if (type == commandRemoved) {
            System.out.println("Command Class removed " + deviceId + ":" + instanceId + " " + commandClassId);
            Device.Instance instance = devices.get(deviceId).instances.get(instanceId);
            instance.commandClasses.remove(commandClassId);
            switch (commandClassId) {
                /* BEGIN AUTOGENERATED CC TEMPLATE
                case %cc_id%:
                    instance.commandClassesByName.remove("%cc_camel_case_name%");
                    break;
                 * END AUTOGENERATED CC TEMPLATE */
            }
        } else {
            System.out.println("Unhandled deviceCallback: type = " + type + ", id = " + deviceId + ", instance = " + instanceId + ", commandClass = " + commandClassId);
        }
    }

    private void terminateCallback() {
        System.out.println("terminateCallback");
    }

    // JNI functions
    private native long jni_zwayInit(String name, String port, int speed, String config_folder, String translations_folder, String zddx_folder, long ternminator_callback);
    private native void jni_discover(long ptr);
    private native boolean jni_isRunning(long ptr);
    private native void jni_addNodeToNetwork(long ptr, boolean startStop);
    private native void jni_removeNodeFromNetwork(long ptr, boolean startStop);
    private native void jni_setDefault(long ptr);
    private native long jni_zdataFind(long dh, String path, long jzway);
    private native long jni_zdataControllerFind(String path, long jzway);
    private native long jni_zdataDeviceFind(String path, int deviceId, long jzway);
    private native long jni_zdataInstanceFind(String path, int deviceId, int instanceId, long jzway);
    private native long jni_zdataCommandClassFind(String path, int deviceId, int instanceId, int commandClassId, long jzway);

    /* BEGIN AUTOGENERATED CC TEMPLATE
     * BEGIN AUTOGENERATED CMD TEMPLATE
    private native void jni_cc_%function_short_camel_case_name%(long ptr, int deviceId, int instanceId, %params_java_declarations%long successCallback, long failureCallback, long callbackArg);
     * END AUTOGENERATED CMD TEMPLATE
     * END AUTOGENERATED CC TEMPLATE */


    public interface DataCallback {
        public void dataCallback(Data data, Integer type);
    }
    
    public final class Data {
        public static final int phantomUpdate = 0x40;
        public static final int childEvent = 0x80;
        public static final int updated = 0x01;
        public static final int invalidated = 0x02;
        public static final int deleted = 0x03;
        public static final int childCreated = 0x04;
        
        public static final int Empty = 0;
        public static final int Bool = 1;
        public static final int Int = 2;
        public static final int Float = 3;
        public static final int String = 4;
        public static final int Binary = 5;
        public static final int IntArray = 6;
        public static final int FloatArray = 7;
        public static final int StringArray = 8;

        private Object value;
        private Type valueType;
        private String valueTypeStr;

        private long dh;

        public final String name;
        public final String path;

        private Boolean isAlive;
        
        private Set<DataCallback> callbacks;
        
        // exceptions
        
        public final class NotAlive extends Throwable {
            public final Data data;
            
            public NotAlive(Data data) {
                super();
                this.data = data;
            }
        }

        public final class NotFound extends Throwable {
            public NotFound() {
                super();
            }
        }

        // constructors
        
        public Data(String path, long dhParent) throws NotFound, Exception {
            this(jni_zdataFind(dhParent, path, jzway));
        }

        public Data(String path) throws NotFound, Exception {
            this(jni_zdataControllerFind(path, jzway));
        }

        public Data(String path, int deviceId) throws NotFound, Exception {
            this(jni_zdataDeviceFind(path, deviceId, jzway));
        }

        public Data(String path, int deviceId, int instanceId) throws NotFound, Exception {
            this(jni_zdataInstanceFind(path, deviceId, instanceId, jzway));
        }

        public Data(String path, int deviceId, int instanceId, int commandClassId) throws NotFound, Exception {
            this(jni_zdataCommandClassFind(path, deviceId, instanceId, commandClassId, jzway));
        }

        private Data(long dh) throws NotFound, Exception {
            if (dh == 0) {
                throw new NotFound();
            }
            this.dh = dh;
            name = jni_zdataGetName(dh);
            path = jni_zdataGetPath(dh);
            isAlive = true;
            callbacks = new HashSet<>();
            jni_zdataAddCallback(dh);
            getValue();
        }

        @Override
        public void finalize() {
            jni_zdataRemoveCallback(dh);
        }

        private void isAlive() throws NotAlive {
            if (!isAlive) {
                throw new NotAlive(this);
            }
        }
        
        public void bind(DataCallback func) throws NotAlive, Exception {
            isAlive();
            
            callbacks.add(func);
        }
        
        public void unbind(DataCallback func) throws NotAlive, Exception {
            isAlive();
            
            callbacks.remove(func);
        }
        
        private void dataCallback(int type) throws Exception {
            // get type of the event
            boolean isPhantom = (phantomUpdate & type) > 0;
            boolean isChild = (childEvent & type) > 0;
            type = type & (~phantomUpdate) & (~childEvent);
            if (type == updated) {
                getValue();
            } else if (type == invalidated) {
                // TODO update invalidate time
            } else if (type == deleted) {
                isAlive = false;
            } else if (type == childCreated) {
                // nothing to do
            } else {
                throw new Exception("Type of the event is an invalid integer.");
            }
            
            for (DataCallback dc : callbacks) {
                dc.dataCallback(this, type);
            }
        }

        private void getValue() throws Exception {
            int dataType = jni_zdataGetType(dh);
            if (dataType == Bool) {
                valueType = Boolean.class;
                valueTypeStr = "Boolean";
                value = jni_zdataGetBoolean(dh);
            } else if (dataType == Int) {
                valueType = Integer.class;
                valueTypeStr = "Integer";
                value = jni_zdataGetInteger(dh);
            } else if (dataType == Float) {
                valueType = Float.class;
                valueTypeStr = "Float";
                value = jni_zdataGetFloat(dh);
            } else if (dataType == String) {
                valueType = String.class;
                valueTypeStr = "String";
                value = jni_zdataGetString(dh);
            } else if (dataType == Binary) {
                valueType = Byte[].class;
                valueTypeStr = "Byte[]";
                int[] val = jni_zdataGetBinary(dh);
                value = Arrays.stream(val).boxed().toArray( Integer[]::new );
            } else if (dataType == IntArray) {
                valueType = Integer[].class;
                valueTypeStr = "Integer[]";
                int[] val = jni_zdataGetIntArray(dh);
                value = Arrays.stream(val).boxed().toArray( Integer[]::new );
            } else if (dataType == FloatArray) {
                valueType = Float[].class;
                valueTypeStr = "Float[]";
                float[] val = jni_zdataGetFloatArray(dh);
                int len = val.length;
                Float[] newValue = new Float[len];
                for (int i = 0; i < len; i++) {
                    newValue[i] = val[i];
                }
                value = newValue;
            } else if (dataType == StringArray) {
                valueType = String[].class;
                valueTypeStr = "String[]";
                value = jni_zdataGetStringArray(dh);
            } else if (dataType == Empty) {
                valueType = Object.class;
                valueTypeStr = "Null";
                value = null;
            } else {
                throw new Exception("Type of the value in data holder is an invalid integer.");
            }
        }

        public Data[] getChildren() throws NotAlive, Exception {
            isAlive();
            
            long[] list = jni_zdataGetChildren(dh);
            int length = list.length;
            Data[] children = new Data[length];
            for (int i = 0; i < length; i++) {
                try {
                    children[i] = new Data(list[i]);
                } catch (NotFound e) {
                    // should never happen
                    throw new RuntimeException();
                }
            }
            return children;
        }
        
        public Data get(String path) throws NotAlive, NotFound, Exception {
            isAlive();
            
            return new Data(path, this.dh);
        }

        public Type getValueType() throws NotAlive {
            isAlive();
            
            return valueType;
        }

        public String getValueTypeStr() throws NotAlive {
            isAlive();
            
            return valueTypeStr;
        }

        public void setBool(Boolean data) throws NotAlive {
            isAlive();
            
            jni_zdataSetBoolean(dh, data);
        }

        public void setInt(Integer data) throws NotAlive {
            isAlive();
            
            jni_zdataSetInteger(dh, data);
        }

        public void setFloat(Float data) throws NotAlive {
            isAlive();
            
            jni_zdataSetFloat(dh, data);
        }

        public void setString(String data) throws NotAlive {
            isAlive();
            
            jni_zdataSetString(dh, data);
        }

        public void setByteList(Integer[] data) throws NotAlive {
            isAlive();
            
            int size = data.length;
            int[] rdata = new int[size];
            for (int i = 0; i < size; i++) {
                rdata[i] = data[i];
            }
            jni_zdataSetBinary(dh, rdata);
        }

        public void setIntList(Integer[] data) throws NotAlive {
            isAlive();
            
            int size = data.length;
            int[] rdata = new int[size];
            for (int i = 0; i < size; i++) {
                rdata[i] = data[i];
            }
            jni_zdataSetIntArray(dh, rdata);
        }

        public void setFloatList(Float[] data) throws NotAlive {
            isAlive();
            
            int size = data.length;
            float[] rdata = new float[size];
            for (int i = 0; i < size; i++) {
                rdata[i] = data[i];
            }
            jni_zdataSetFloatArray(dh, rdata);
        }

        public void setStringList(String[] data) throws NotAlive {
            isAlive();

            jni_zdataSetStringArray(dh, data);
        }

        public void setEmpty() throws NotAlive {
            isAlive();
            
            jni_zdataSetEmpty(dh);
        }

        public Boolean getBool() throws NotAlive {
            isAlive();
            
            if (valueType == Boolean.class && valueTypeStr.equals("Boolean")) {
                return (Boolean) value;
            } else {
                throw new ClassCastException("Illegal call: value is not Boolean");
            }
        }

        public Integer getInt() throws NotAlive {
            isAlive();
            
            if (valueType == Integer.class && valueTypeStr.equals("Integer")) {
                return (Integer) value;
            } else {
                throw new ClassCastException("Illegal call: value is not Integer");
            }
        }

        public Float getFloat() throws NotAlive {
            isAlive();
            
            if (valueType == Float.class && valueTypeStr.equals("Float")) {
                return (Float) value;
            } else {
                throw new ClassCastException("Illegal call: value is not Float");
            }
        }

        public String getString() throws NotAlive {
            isAlive();
            
            if (valueType == String.class && valueTypeStr.equals("String")) {
                return (String) value;
            } else {
                throw new ClassCastException("Illegal call: value is not String");
            }
        }

        public Integer[] getByteList() throws NotAlive {
            isAlive();
            
            if (valueType == Byte[].class && valueTypeStr.equals("Byte[]")) {
                return (Integer[]) value;
            } else {
                throw new ClassCastException("Illegal call: value is not Integer[]");
            }
        }

        public Integer[] getIntList() throws NotAlive {
            isAlive();
            
            if (valueType == Integer[].class && valueTypeStr.equals("Integer[]")) {
                return (Integer[]) value;
            } else {
                throw new ClassCastException("Illegal call: value is not Integer[]");
            }
        }

        public Float[] getFloatList() throws NotAlive {
            isAlive();
            
            if (valueType == Float[].class && valueTypeStr.equals("Float[]")) {
                return (Float[]) value;
            } else {
                throw new ClassCastException("Illegal call: value is not Float[]");
            }
        }

        public String[] getStringList() throws NotAlive {
            isAlive();
            
            if (valueType == String[].class && valueTypeStr.equals("String[]")) {
                return (String[]) value;
            } else {
                throw new ClassCastException("Illegal call: value is not String[]");
            }
        }

        // JNI functions
        private native void jni_zdataAddCallback(long dh);
        private native void jni_zdataRemoveCallback(long dh);
        private native String jni_zdataGetName(long data);
        private native int jni_zdataGetType(long dh);
        private native boolean jni_zdataGetBoolean(long dh);
        private native int jni_zdataGetInteger(long dh);
        private native float jni_zdataGetFloat(long dh);
        private native String jni_zdataGetString(long dh);
        private native int[] jni_zdataGetBinary(long dh);
        private native int[] jni_zdataGetIntArray(long dh);
        private native float[] jni_zdataGetFloatArray(long dh);
        private native String[] jni_zdataGetStringArray(long dh);
        private native void jni_zdataSetEmpty(long dh);
        private native void jni_zdataSetBoolean(long dh, boolean data);
        private native void jni_zdataSetInteger(long dh, int data);
        private native void jni_zdataSetFloat(long dh, float data);
        private native void jni_zdataSetString(long dh, String data);
        private native void jni_zdataSetBinary(long dh, int[] data);
        private native void jni_zdataSetIntArray(long dh, int[] data);
        private native void jni_zdataSetFloatArray(long dh, float[] data);
        private native void jni_zdataSetStringArray(long dh, String[] data);
        private native long[] jni_zdataGetChildren(long dh);
        private native String jni_zdataGetPath(long dh);
    }

    public final class Controller {
        public final Data data;

        public Controller() throws Exception {
            try {
                data = new Data("");
            } catch (Data.NotFound e) {
                // should never happen
                throw new RuntimeException();
            }
        }
        
        public void addNodeToNetwork(boolean startStop) {
            jni_addNodeToNetwork(jzway, startStop);
        }

        public void removeNodeFromNetwork(boolean startStop) {
            jni_removeNodeFromNetwork(jzway, startStop);
        }

        public void setDefault() {
            jni_setDefault(jzway);
        }
    }

    public final class Device {
        public final Integer id;
        public final Data data;

        public Map<Integer, Instance> instances;

        public Device(ZWay zway, Integer device_id) throws Exception {
            id = device_id;
            try {
                data = new Data("", device_id);
            } catch (Data.NotFound e) {
                // should never happen
                throw new RuntimeException();
            }
            instances = new HashMap<>();
        }

        public final class Instance {
            private final Device device;

            public final Integer id;
            public final Data data;

            public Map<Integer, CommandClass> commandClasses;
            public Map<String, CommandClass> commandClassesByName;
            
            public Instance(ZWay zway, Device dev, Integer instance_id) throws Exception {
                device = dev;
                id = instance_id;
                try {
                    data = new Data("", dev.id, instance_id);
                } catch (Data.NotFound e) {
                    // should never happen
                    throw new RuntimeException();
                }
                commandClasses = new HashMap<>();
                commandClassesByName = new HashMap<>();
            }

            public class CommandClass {
                protected final Instance instance;

                public final Data data = null;
                
                public CommandClass(ZWay zway, Instance inst) throws Exception {
                    instance = inst;
                }
            }

            /* BEGIN AUTOGENERATED CC TEMPLATE
            public final class %cc_capitalized_name% extends CommandClass {
                public final static int id = %cc_id%;
                public final Data data;

                public %cc_capitalized_name%(ZWay zway, Instance instance) throws Exception {
                    super(zway, instance);
                    try {
                        data = new Data("", instance.device.id, instance.id, %cc_id%);
                    } catch (Data.NotFound e) {
                        // should never happen
                        throw new RuntimeException();
                    }
                }

             * BEGIN AUTOGENERATED CMD TEMPLATE
                public void %function_command_camel_name%(%params_java_declarations%long successCallback, long failureCallback, long callbackArg) {
                    jni_cc_%function_short_camel_case_name%(jzway, instance.device.id, instance.id, %params%successCallback, failureCallback, callbackArg);
                }
                public void %function_command_camel_name%(%params_java_declarations_no_comma%) {
                    jni_cc_%function_short_camel_case_name%(jzway, instance.device.id, instance.id, %params%0, 0, 0);
                }
                
             * END AUTOGENERATED CMD TEMPLATE
            }
            
             * END AUTOGENERATED CC TEMPLATE */
        }
    }
}
