# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 2.7
      run: sudo apt-get install python2
    - name: Install Z-Way
      run: wget -qO - https://storage.z-wave.me/Z-Way-Install | sudo bash
    - name: Check Z-Way version
      run: |
        export ZWAY_VER=$(cd /opt/z-way-server && ./z-way-server --version | sed 's/Z-Way version v\([^ ]*\) .*/\1/')
        export PKG_VER=$(cat pom.xml | grep version | head -n 1 | sed '0,/<version>/ { s|.*<version>\(.*\)</version>.*|\1| }')
        echo "Z-Way version:   ${ZWAY_VER}"
        echo "Package version: ${PKG_VER}"
        test "${ZWAY_VER}" == "${PKG_VER}" || true
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Deploy with Maven
      run: mvn -B clean deploy -Pci-cd
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
